# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'BeenHere' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	platform :ios, '9.0'
	pod 'Firebase'
	pod 'Firebase/Auth'
	pod 'FirebaseUI/Google'
	pod 'FirebaseUI/Facebook'
	pod 'FirebaseUI'
	pod 'Firebase/Core'
	pod 'Firebase/Storage'
	pod 'GoogleSignIn'
  # Pods for BeenHere

end
